language: go

sudo: false

go:
    - 1.8.x
    - 1.9.x
    - 1.10.x
    - tip

matrix:
    fast_finish: true
    allow_failures:
        - go: tip

before_install:
    - mkdir -p $HOME/bin
    - curl -sL https://get.binhq.io/binbrew | DEST=$HOME/bin NAME=bin bash
    - bin get golang/dep@0.4.1 $HOME/bin

install: dep ensure -vendor-only

script: go test
