[prune]
  go-tests = true
  unused-packages = true

[[constraint]]
  name = "github.com/alecthomas/kingpin"
  version = "2.2.6"

[[constraint]]
  name = "github.com/fsnotify/fsnotify"
  version = "1.4.7"
